
-- Insert 10 diverse example opportunities
INSERT INTO opportunities (title, description, category, sector, company_name, location, business_sector, website_url, salary_range, deadline, is_featured, is_active) VALUES
('Senior Software Engineer - FinTech', 'Join our innovative fintech startup building the future of digital banking. We are looking for experienced engineers passionate about creating scalable solutions.', 'career', 'private', 'NeoBank Solutions', 'London, UK', 'Financial Services', 'https://example.com', '£60,000 - £85,000', '2025-11-15', true, true),
('Export Partnership Opportunity', 'UK Government initiative supporting businesses to expand into African markets. Funding and mentorship available for qualifying enterprises.', 'business', 'public', 'Department for International Trade', 'Manchester, UK', 'Trade & Export', 'https://example.com', NULL, '2025-10-30', true, true),
('Series A Investment - EdTech Platform', 'Seeking £2M investment for innovative education platform serving diaspora communities. Strong traction with 50K+ users across 15 countries.', 'investment', 'private', 'LearnConnect Global', 'Birmingham, UK', 'Education Technology', 'https://example.com', '£1M - £3M', '2025-11-30', false, true),
('Cultural Festival Collaboration', 'Partner with us to organize the UK''s largest multicultural festival celebrating diaspora heritage. Looking for sponsors, vendors, and community partners.', 'collaboration', 'private', 'Unity Festival Ltd', 'London, UK', 'Arts & Culture', 'https://example.com', NULL, '2025-10-20', false, true),
('Digital Marketing Manager', 'Lead marketing efforts for a social enterprise empowering underrepresented entrepreneurs. Remote-friendly with quarterly team meetups.', 'career', 'private', 'Impact Ventures UK', 'Remote / London', 'Social Enterprise', 'https://example.com', '£45,000 - £55,000', '2025-11-05', false, true),
('Green Energy Grant Programme', 'Local authority offering grants up to £100K for sustainable business initiatives. Priority given to minority-owned enterprises.', 'business', 'public', 'Greater Manchester Combined Authority', 'Manchester, UK', 'Energy & Sustainability', 'https://example.com', NULL, '2025-10-25', true, true),
('Seed Funding - Healthcare Innovation', 'Angel investors seeking healthcare startups addressing health disparities in diverse communities. Ticket size £100K-£500K.', 'investment', 'private', 'Health Equity Angels', 'London, UK', 'Healthcare', 'https://example.com', '£100K - £500K', '2025-12-15', false, true),
('University Research Partnership', 'Collaborate on groundbreaking research exploring economic impact of diaspora entrepreneurship. Funded 2-year programme.', 'collaboration', 'public', 'University of Salford', 'Salford, UK', 'Research & Education', 'https://example.com', NULL, '2025-11-10', false, true),
('Head of Community Engagement', 'Shape the future of diaspora business support programmes. Lead a passionate team making real impact across the UK.', 'career', 'private', 'Our Business Greater Manchester', 'Manchester, UK', 'Business Support', 'https://example.com', '£50,000 - £65,000', '2025-10-28', false, true),
('Tech Accelerator Programme', 'Factory International backing tech founders from underrepresented backgrounds. 12-week intensive with £25K investment and mentorship.', 'business', 'private', 'Factory International', 'Manchester, UK', 'Technology', 'https://example.com', NULL, '2025-11-01', true, true);
