// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtrqojsqscnloymlwwpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cnFvanNxc2NubG95bWx3d3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzU3ODcsImV4cCI6MjA3MTExMTc4N30.rbD0gD4lr_AmfvBsdNhJBSgmse9U4Jx6-Au9hkA8DY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});